<h1 align = "Center">
Lotus Group Customer Behavior Analysis

<h2 align = "Center">
Data Inventory
</h1>

In [3]:

import pandas as pd
from pathlib import Path

# Define path to folder
data_path = Path(r"../01_data/raw")

def load_csv (filename):
    return pd.read_csv(data_path/filename)

# Display the files available
for file in sorted(data_path.iterdir()):
    if file.is_file():
        print(file.name)

tbl_customers.csv
tbl_date.csv
tbl_employees.csv
tbl_order_details.csv
tbl_orders_2022_2023.csv
tbl_orders_2024.csv
tbl_products.csv
tbl_returns.csv
tbl_stores.csv

In [4]:

# Load customers table
customers = load_csv("tbl_customers.csv")
customers.head()

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
0,CUS01518,Mohamed Mansour,Male,1981-05-01,1158132110,mohamed.mansour52@hotmail.com,Suez,Canal Zone,Bronze,2020-12-19
1,CUS02370,Maged Lotfy,Male,2003-04-10,1281872177,NaN,Zagazig,Nile Delta,Bronze,2021-05-13
2,CUS01962,Ahmed Hafez,Male,1971-05-03,1141856715,ahmed.hafez18@outlook.com,Giza,Greater Cairo,Gold,2023-09-26
3,CUS00344,Hoda Fathy,Female,2000-05-19,1195645083,hoda.fathy26@outlook.com,Giza,Greater Cairo,Bronze,2021-07-07
4,CUS02664,Hussein Lotfy,MALE,1998-12-26,1149528740,hussein.lotfy80@gmail.com,Tanta,Nile Delta,Bronze,2022-10-05

In [5]:
# Load date table
date = load_csv("tbl_date.csv")
date.head()

,date_id,full_date,day,month,month_name,quarter,quarter_name,year,day_of_week,day_name,is_weekend,week_of_year,is_ramadan
0,20220101,2022-01-01,1,1,January,1,Q1,2022,6,Saturday,1,52,0
1,20220102,2022-01-02,2,1,January,1,Q1,2022,7,Sunday,0,52,0
2,20220103,2022-01-03,3,1,January,1,Q1,2022,1,Monday,0,1,0
3,20220104,2022-01-04,4,1,January,1,Q1,2022,2,Tuesday,0,1,0
4,20220105,2022-01-05,5,1,January,1,Q1,2022,3,Wednesday,0,1,0

In [6]:
# Load employees table
employees = load_csv("tbl_employees.csv")
employees.head()

,employee_id,first_name,last_name,gender,role,store_id,hire_date,monthly_salary_egp
0,EMP0001,Ghada,Sayed,Female,Store Manager,1,2018-07-04,14235
1,EMP0002,Nadia,Ali,Female,Sales Associate,1,2023-08-18,4255
2,EMP0003,Samah,Mahmoud,Female,Sales Associate,1,2022-05-27,5287
3,EMP0004,Neveen,Ismail,Female,Store Manager,1,2023-02-02,14854
4,EMP0005,Samir,Mahmoud,Male,Department Manager,1,2024-04-28,8706

In [7]:
# Load products table
products = load_csv("tbl_products.csv")
products.head()

,product_id,product_name_raw,category,subcategory,brand,unit_price_text,unit_price,unit_cost,stock_qty,is_active
0,CLT0001,T-Shirt | Black | S,Clothing,Tops,Nile Fashion,EGP 90,90,40,449,1
1,CLT0002,T-Shirt | Black | M,Clothing,Tops,Nile Fashion,EGP 90,90,40,94,1
2,CLT0003,T-Shirt | Black | L,Clothing,Tops,Nile Fashion,EGP 90,90,40,444,1
3,CLT0004,T-Shirt | Black | XL,Clothing,Tops,Nile Fashion,EGP 90,90,40,408,1
4,CLT0005,T-Shirt | White | S,Clothing,Tops,Nile Fashion,EGP 90,90,40,22,1

In [8]:
# Load stores table
stores = load_csv("tbl_stores.csv")
stores.head()

,store_id,store_name,city,district,region,opening_year,size_sqm,store_type
0,1,Lotus Cairo Festival City,Cairo,New Cairo,Greater Cairo,2018,420,Flagship
1,2,Lotus Mall of Egypt,Giza,Sheikh Zayed,Greater Cairo,2019,380,Flagship
2,3,Lotus City Stars,Cairo,Nasr City,Greater Cairo,2017,350,Flagship
3,4,Lotus Alexandria City Centre,Alexandria,Smouha,Alexandria,2020,290,Standard
4,5,Lotus San Stefano,Alexandria,San Stefano,Alexandria,2016,310,Standard

In [9]:
# Load order details table
order_details = load_csv("tbl_order_details.csv")
order_details.head()

,detail_id,order_id,product_id,quantity,unit_price,discount_pct,selling_price,unit_cost,line_total_revenue,line_total_cost
0,DTL0000001,ORD0000001,CLT0168,1,460,10,414.0,220,414.0,220
1,DTL0000002,ORD0000001,CLT0248,1,210,25,157.5,100,157.5,100
2,DTL0000003,ORD0000001,CLT0198,1,240,0,240.0,110,240.0,110
3,DTL0000004,ORD0000001,CLT0167,1,450,0,450.0,220,450.0,220
4,DTL0000005,ORD0000002,CLT0157,2,830,0,830.0,410,1660.0,820

In [10]:
# Load 2022-2023 orders table
orders_2022_2023 = load_csv("tbl_orders_2022_2023.csv")
orders_2022_2023.head()

,order_id,order_date,date_id,customer_id,store_id,employee_id,payment_method,order_status,total_revenue,total_cost
0,ORD0003830,2022-01-01,20220101,CUS01700,4,EMP0089,Debit Card,Completed,840.0,460.0
1,ORD0001773,2022-01-01,20220101,CUS01029,2,EMP0047,Debit Card,Completed,1332.0,740.0
2,ORD0011987,2022-01-01,20220101,CUS02153,11,EMP0173,Debit Card,Completed,520.0,260.0
3,ORD0009735,2022-01-01,20220101,CUS00424,2,EMP0043,Cash,Completed,344.0,210.0
4,ORD0007544,2022-01-01,20220101,CUS01849,10,EMP0160,Vodafone Cash,Completed,1408.0,740.0

In [11]:
# Load 2024 orders table
orders_2024 = load_csv("tbl_orders_2024.csv")
orders_2024.head()

,order_id,order_date,date_id,customer_id,store_id,employee_id,payment_method,order_status,total_revenue,total_cost
0,ORD0002861,2024-01-01,20240101,CUS00888,4,EMP0079,Credit Card,Returned,5302.0,4310.0
1,ORD0006046,2024-01-01,20240101,CUS02416,1,EMP0009,InstaPay,Completed,740.0,360.0
2,ORD0002658,2024-01-01,20240101,CUS02527,12,EMP0175,Cash,Completed,1771.0,880.0
3,ORD0008080,2024-01-01,20240101,CUS00340,11,EMP0171,Cash,Completed,3485.0,2010.0
4,ORD0009278,2024-01-01,20240101,CUS00906,6,EMP0116,Debit Card,Completed,233.0,120.0

In [12]:
# Load returns table
returns = load_csv("tbl_returns.csv")
returns.head()

,return_id,order_id,return_date,return_reason,return_amount,refund_method,return_status
0,RET00001,ORD0000010,2022-05-23,Defective Product,85.0,Fawry,Refunded
1,RET00002,ORD0000017,2024-03-20,Duplicate Order,8285.0,InstaPay,Refunded
2,RET00003,ORD0000029,2023-07-08,Wrong Item Delivered,180.0,Vodafone Cash,Refunded
3,RET00004,ORD0000039,2022-08-28,Changed Mind,1705.0,Cash,Pending
4,RET00005,ORD0000052,2023-06-04,Changed Mind,2000.0,Cash,Refunded

### Data Inventory

With all tables loaded, we can now create a data inventory that documents the actual structure of each table

In [13]:

datasets = {
    "customers": customers,
    "date": date,
    "employees": employees,
    "products": products,
    "stores": stores,
    "order_details": order_details,
    "orders_2022_2023": orders_2022_2023,
    "orders_2024": orders_2024,
    "returns": returns
}

for name, df in datasets.items():
    print(f"\n{'=' * 50}")
    print(f"Table: {name}")
    print(f"Rows: {df.shape[0]:,}")
    print(f"Columns: {df.shape[1]}")
    print("Column names:")
    print(df.columns.tolist())

==================================================
Table: customers
Rows: 3,050
Columns: 10
Column names:
['customer_id', 'full_name', 'gender', 'birth_date', 'phone', 'email', 'city', 'region', 'loyalty_tier', 'registration_date']

==================================================
Table: date
Rows: 1,096
Columns: 13
Column names:
['date_id', 'full_date', 'day', 'month', 'month_name', 'quarter', 'quarter_name', 'year', 'day_of_week', 'day_name', 'is_weekend', 'week_of_year', 'is_ramadan']

==================================================
Table: employees
Rows: 216
Columns: 8
Column names:
['employee_id', 'first_name', 'last_name', 'gender', 'role', 'store_id', 'hire_date', 'monthly_salary_egp']

==================================================
Table: products
Rows: 345
Columns: 10
Column names:
['product_id', 'product_name_raw', 'category', 'subcategory', 'brand', 'unit_price_text', 'unit_price', 'unit_cost', 'stock_qty', 'is_active']

==================================================
Table: stores
Rows: 15
Columns: 8
Column names:
['store_id', 'store_name', 'city', 'district', 'region', 'opening_year', 'size_sqm', 'store_type']

==================================================
Table: order_details
Rows: 25,099
Columns: 10
Column names:
['detail_id', 'order_id', 'product_id', 'quantity', 'unit_price', 'discount_pct', 'selling_price', 'unit_cost', 'line_total_revenue', 'line_total_cost']

==================================================
Table: orders_2022_2023
Rows: 7,942
Columns: 10
Column names:
['order_id', 'order_date', 'date_id', 'customer_id', 'store_id', 'employee_id', 'payment_method', 'order_status', 'total_revenue', 'total_cost']

==================================================
Table: orders_2024
Rows: 4,058
Columns: 10
Column names:
['order_id', 'order_date', 'date_id', 'customer_id', 'store_id', 'employee_id', 'payment_method', 'order_status', 'total_revenue', 'total_cost']

==================================================
Table: returns
Rows: 1,056
Columns: 7
Column names:
['return_id', 'order_id', 'return_date', 'return_reason', 'return_amount', 'refund_method', 'return_status']